// <auto-generated />
using System;
using Limbo.MailSystem.Persisence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Limbo.MailSystem.Persisence.Migrations
{
    [DbContext(typeof(MailContext))]
    partial class MailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Limbo.MailSystem.Persisence.MailSegments.Models.MailSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MailTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("NVarCharMaxValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVarCharValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("SegmentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MailTemplateId");

                    b.HasIndex("SegmentTypeId");

                    b.ToTable("Limbo_Mail_MailSegments");
                });

            modelBuilder.Entity("Limbo.MailSystem.Persisence.MailTemplates.Models.MailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Limbo_Mail_MailTemplates");
                });

            modelBuilder.Entity("Limbo.MailSystem.Persisence.SegmentTypes.Models.SegmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Limbo_Mail_SegmentTypes");
                });

            modelBuilder.Entity("Limbo.MailSystem.Persisence.MailSegments.Models.MailSegment", b =>
                {
                    b.HasOne("Limbo.MailSystem.Persisence.MailTemplates.Models.MailTemplate", "MailTemplate")
                        .WithMany("MailSegments")
                        .HasForeignKey("MailTemplateId");

                    b.HasOne("Limbo.MailSystem.Persisence.SegmentTypes.Models.SegmentType", "SegmentType")
                        .WithMany("MailSegments")
                        .HasForeignKey("SegmentTypeId");

                    b.Navigation("MailTemplate");

                    b.Navigation("SegmentType");
                });

            modelBuilder.Entity("Limbo.MailSystem.Persisence.MailTemplates.Models.MailTemplate", b =>
                {
                    b.Navigation("MailSegments");
                });

            modelBuilder.Entity("Limbo.MailSystem.Persisence.SegmentTypes.Models.SegmentType", b =>
                {
                    b.Navigation("MailSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
